[project]
name = "moe-prs-paper"
version = "0.1.0"
description = "Mixture of Experts for Polygenic risk prediction"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "joblib>=1.5.3",
    "liftover>=1.4.0",
    "lightning>=2.6.4",
    "magenpy>=0.1",
    "matplotlib>=3.10.9",
    "numpy>=1.26.4",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "torch>=2.12.0",
    "tqdm>=4.67.3",
    "viprs>=0.1",
]
